Issue #3177657 by tBKoT: Add posibility to filter KPI by terms. Code …
goalgorilla/kpi_analytics pull request #12
Opened 2020-10-23 10:48 UTC by dmytriikaiun

…refactoring.

2020-10-29 18:27 UTC, ribel commented on assets/js/morris-chart.js
> +      $('div.morris_chart').once('renderChart').each(function () {
@dmytriikaiun could you explain why do you make this change?

2020-10-29 18:33 UTC, ribel requested changes
@dmytriikaiun, In general, all looks good to me, just have few minor questions.

2020-10-29 18:33 UTC, ribel commented on src/Plugin/Block/KPIBlockContentBlock.php
> +        '#type' => 'select2',
@dmytriikaiun I think we need to add a dependency from select2 in this case.

2020-10-29 18:33 UTC, ribel commented on src/Plugin/KPIDatasource/DrupalKPIDatasource.php
>      // TODO: deprecated use dependency injection.
@dmytriikaiun I think we can remove this TODO now, since we started to use DI?

2020-10-30 11:08 UTC, dmytriikaiun commented on assets/js/morris-chart.js
> +      $('div.morris_chart').once('renderChart').each(function () {
@ribel it fix this issue -> https://getopensocial.atlassian.net/browse/YANG-4023
Sometimes `context`  not correct.

2020-10-30 11:08 UTC, dmytriikaiun commented on src/Plugin/Block/KPIBlockContentBlock.php
> +        '#type' => 'select2',
Ok

2020-10-30 11:08 UTC, dmytriikaiun commented on src/Plugin/KPIDatasource/DrupalKPIDatasource.php
>      // TODO: deprecated use dependency injection.
Yes, I guess we can

2020-10-30 13:21 UTC, ribel approved these changes

2020-11-04 15:11 UTC, merged